[build]
target = "x86_64-unknown-uefi"

[target.'cfg(target_os = "uefi")']
runner = "./test.sh"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
